services:
  frontend: 
    build: 
      context: .
      dockerfile: apps/workspace-fe/Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        VITE_WEBSOCKET_URL: ${VITE_WEBSOCKET_URL}
        VITE_ICE_SERVERS_URL: ${VITE_ICE_SERVERS_URL}
        VITE_KEYCLOAK_URL: ${VITE_KEYCLOAK_URL}
        VITE_KEYCLOAK_REALM: ${VITE_KEYCLOAK_REALM}
        VITE_KEYCLOAK_CLIENT_ID: ${VITE_KEYCLOAK_CLIENT_ID}
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: 
      context: .
      dockerfile: apps/workspace-be/Dockerfile
    ports:
      - "3500:3500"
    environment:
      - PORT=3500
      - MONGODB_URI=${MONGODB_URI}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - CLIENT_URL=${VITE_BACKEND_URL}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}