FROM node:22-alpine as builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY vite.config.js index.html ./
COPY src/ ./src/
COPY public/ ./public/

ARG VITE_BACKEND_URL
ARG VITE_WEBSOCKET_URL
ARG VITE_ICE_SERVERS_URL

ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
ENV VITE_WEBSOCKET_URL=$VITE_WEBSOCKET_URL
ENV VITE_ICE_SERVERS_URL=$VITE_ICE_SERVERS_URL

RUN npm run build

#serve NGINX
FROM nginx:alpine as runner

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]