name: CI

on:
  pull_request:
    branches: [main, staging]

concurrency:
  group: ci-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint (turbo)
        run: npm run lint

  unit-test:
    name: Unit Tests (Backend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Jest
        run: npm run test
        working-directory: apps/workspace-be

  e2e-test:
    name: E2E Tests (Frontend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('apps/workspace-fe/package-lock.json') }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        working-directory: apps/workspace-fe

      - name: Run Playwright E2E
        run: npx playwright test
        working-directory: apps/workspace-fe
        env:
          BASE_URL: ${{ secrets.STAGING_FRONTEND_URL }}
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: failure()
        # upload when test fail
        with:
          name: playwright-report
          path: apps/workspace-fe/playwright-report/
          retention-days: 7
